import { error } from 'node:console'

const nzCities = [
	'auckland',
	'christchurch',
	'manukau city',
	'wellington',
	'northcote',
	'hamilton',
	'tauranga',
	'lower hutt',
	'dunedin',
	'palmerston north',
	'napier',
	'new plymouth',
	'porirua',
	'rotorua',
	'whangarei',
	'invercargill',
	'nelson',
	'upper hutt',
	'gisborne',
	'paraparaumu',
	'timaru',
	'blenheim',
	'taupo',
	'cambridge',
	'feilding',
	'levin',
	'rolleston',
	'whakatane',
	'richmond',
	'havelock north',
	'tokoroa',
	'mosgiel',
	'te awamutu',
	'waikanae',
	'hawera',
	'waiuku',
	'paraparaumu beach',
	'wanaka',
	'te puke',
	'greymouth',
	'matamata',
	'thames',
	'kawerau',
	'kerikeri',
	'waitara',
	'ngaruawahia',
	'mount maunganui',
	'lincoln',
	'kaitaia',
	'stratford',
	'alexandra',
	'cromwell',
	'warkworth',
	'waihi',
	'raumati beach',
	'marton',
	'whitianga',
	'tuakau',
	'dargaville',
	'katikati',
	'westport',
	'tauwhare',
	'te aroha',
	'kaikohe',
	'prebbleton',
	'paeroa',
	'whangamata',
	'balclutha',
	'snells beach',
	'turangi',
	'raglan',
	'foxton',
	'darfield',
	'ashhurst',
	'hokitika',
	'helensville',
	'woodend',
	'kihikihi',
	'pahiatua',
	'wakefield',
	'ruakaka',
	'winton',
	'maraetai',
	'te anau',
	'clive',
	'oxford',
	'pokeno',
	'milton',
	'waihi beach',
	'brightwater',
	'leeston',
	'west melton',
	'waitangi',
]

export function validateCity(city: string): string | null {
	if (!nzCities.includes(city.toLowerCase())) {
		return 'Make sure you enter a NZ city'
	}
	return null
}
